POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Arjun",
   "number": "545646"
}

###
PUT http://localhost:3001/api/persons/2
Content-Type: application/json

{
   "name": "Mary",
   "number": "1230"
}