POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Ar",
   "number": "545646"
}

###
PUT http://localhost:3001/api/persons/6571ae145fab66b17e01b013
Content-Type: application/json

{
   "name": "arjun",
   "number": "1230"
}